"""make github_id nullable

Revision ID: 9b7880da1d81
Revises: a64bac0fcff4
Create Date: 2026-03-05 09:43:09.792552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b7880da1d81'
down_revision: Union[str, None] = 'a64bac0fcff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('repos', 'github_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('repos', 'github_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
